# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0002_auto_20170116_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFiles',
            new_name='FileUpload',
        ),
    ]
