# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0003_auto_20170116_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='JS',
            field=models.ImageField(blank=True, help_text='JS file will be stored on /static/js folder', upload_to='C:\\Django\\site_amr/amr/static/js'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='CSS',
            field=models.ImageField(blank=True, help_text='CSS file will be stored on /static/css folder', upload_to='C:\\Django\\site_amr/amr/static/css'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='Image',
            field=models.ImageField(blank=True, help_text='Image file will be stored on /static/images folder', upload_to='C:\\Django\\site_amr/amr/static/images'),
        ),
    ]
