# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0005_auto_20170116_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=255)),
                ('div_tag', models.CharField(blank=True, help_text='Please specify div tag.', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='Image',
            field=models.ImageField(blank=True, help_text='Image file will be stored on /static/images folder', upload_to='C:\\Django\\site_amr/amr/static/images'),
        ),
    ]
