# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0007_auto_20170118_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttable',
            name='TableImage',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
