# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0008_auto_20170118_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableHeaderBigText', models.CharField(blank=True, max_length=255)),
                ('TableHeaderText', models.TextField(blank=True, max_length=255)),
                ('FirstRowHeader', models.CharField(blank=True, max_length=255)),
                ('FirstRowText', models.TextField(blank=True, max_length=255)),
                ('SecondRowHeader', models.CharField(blank=True, max_length=255)),
                ('SecondRowText', models.TextField(blank=True, max_length=255)),
                ('ThirdRowHeader', models.CharField(blank=True, max_length=255)),
                ('ThirdRowText', models.TextField(blank=True, max_length=255)),
                ('FourthRowHeader', models.CharField(blank=True, max_length=255)),
                ('FourthRowText', models.TextField(blank=True, max_length=255)),
                ('FifthRowHeader', models.CharField(blank=True, max_length=255)),
                ('FifthRowText', models.TextField(blank=True, max_length=255)),
                ('SixthRowHeader', models.CharField(blank=True, max_length=255)),
                ('SixtRowText', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
