# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0009_secondtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableHeaderBigText', models.CharField(blank=True, max_length=255)),
                ('TableHeaderText', models.TextField(blank=True, max_length=255)),
                ('FirstRowHeader', models.CharField(blank=True, max_length=255)),
                ('FirstRowText', models.TextField(blank=True, max_length=255)),
                ('Choose1', models.CharField(blank=True, max_length=100)),
                ('Choose2', models.CharField(blank=True, max_length=100)),
                ('Choose3', models.CharField(blank=True, max_length=100)),
                ('Choose4', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
