# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0012_thirdtable_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableHeaderBigText', models.CharField(blank=True, max_length=255)),
                ('TableHeaderText', models.TextField(blank=True, max_length=255)),
                ('Circle1', models.CharField(blank=True, max_length=100)),
                ('Circle2', models.CharField(blank=True, max_length=100)),
                ('Circle3', models.CharField(blank=True, max_length=100)),
                ('Circle4', models.CharField(blank=True, max_length=100)),
                ('Circle5', models.CharField(blank=True, max_length=100)),
                ('Circle6', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
