# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0013_fourthtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifthTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableHeaderBigText', models.CharField(blank=True, max_length=255)),
                ('TableHeaderText', models.TextField(blank=True, max_length=255)),
                ('Column_1_Image', models.ImageField(blank=True, upload_to='static/images')),
                ('Column_1_Header', models.CharField(blank=True, max_length=255)),
                ('Column_1_Text', models.CharField(blank=True, max_length=255)),
                ('Column_2_Image', models.ImageField(blank=True, upload_to='static/images')),
                ('Column_2_Header', models.CharField(blank=True, max_length=255)),
                ('Column_2_Text', models.CharField(blank=True, max_length=255)),
                ('Column_3_Image', models.ImageField(blank=True, upload_to='static/images')),
                ('Column_3_Header', models.CharField(blank=True, max_length=255)),
                ('Column_3_Text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
