# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0014_fifthtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifthtable',
            name='Column_1_Text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fifthtable',
            name='Column_2_Text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fifthtable',
            name='Column_3_Text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
