# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0015_auto_20170119_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_1_Header',
            new_name='Column1Header',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_1_Image',
            new_name='Column1Image',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_1_Text',
            new_name='Column1Text',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_2_Header',
            new_name='Column2Header',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_2_Image',
            new_name='Column2Image',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_2_Text',
            new_name='Column2Text',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_3_Header',
            new_name='Column3Header',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_3_Image',
            new_name='Column3Image',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column_3_Text',
            new_name='Column3Text',
        ),
    ]
