# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0016_auto_20170119_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifthtable',
            name='Column1Image',
            field=models.ImageField(blank=True, upload_to='site_amr/amr/static/images'),
        ),
    ]
