# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0017_auto_20170119_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column1Header',
            new_name='Column1_Header',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column1Text',
            new_name='Column1_Text',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column2Header',
            new_name='Column2_Header',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column2Image',
            new_name='Column2_Image',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column2Text',
            new_name='Column2_Text',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column3Header',
            new_name='Column3_Header',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column3Image',
            new_name='Column3_Image',
        ),
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Column3Text',
            new_name='Column3_Text',
        ),
        migrations.RemoveField(
            model_name='fifthtable',
            name='Column1Image',
        ),
        migrations.AddField(
            model_name='fifthtable',
            name='Column1_Image',
            field=models.ImageField(blank=True, upload_to='/static/images'),
        ),
    ]
