# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0019_auto_20170119_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifthtable',
            old_name='Image',
            new_name='Column1_Image',
        ),
    ]
