# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0020_auto_20170119_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifthtable',
            name='Column1_Image',
            field=models.ImageField(blank=True, height_field='303', upload_to='static/images', width_field='555'),
        ),
        migrations.AlterField(
            model_name='fifthtable',
            name='Column2_Image',
            field=models.ImageField(blank=True, height_field='301', upload_to='static/images', width_field='263'),
        ),
        migrations.AlterField(
            model_name='fifthtable',
            name='Column3_Image',
            field=models.ImageField(blank=True, height_field='301', upload_to='static/images', width_field='263'),
        ),
        migrations.AlterField(
            model_name='firsttable',
            name='TableImage',
            field=models.ImageField(blank=True, height_field='557', upload_to='static/images', width_field='510'),
        ),
    ]
