# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr', '0023_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
